### ISSUE TITLE
Incremental filter build

### ISSUE THREAD

**Issue by Zabrane** [mpope9/efuse_filter#5]
Hi @mpope9 
Can `efuse_filter` support incremental build as with [exor_filter](https://github.com/mpope9/exor_filter?tab=readme-ov-file#incremental-initialization) ?

**Comment by mpope9** [comment]
@Zabrane it has been quite a while since I last touched this but I believe so: https://github.com/mpope9/efuse_filter?tab=readme-ov-file#incremental-initialization

```
Filter0 = fuse8:new_empty(),

%% Add multiple elements.
Filter1 = fuse8:add(Filter0, [1, 2]),
Filter2 = fuse8:add(Filter1, [3, 4]),

%% Add single element.
Filter3 = fuse8:add(Filter2, 5),

Filter4 = fuse8:finalize(Filter3),

true = fuse8:contain(Filter4, 1),
false = fuse8:contain(Filter4, 6).
```

**Comment by mpope9** [comment]
Closing this one 😄
